name: docker-build-metadata-action
description: Parse output metadata of docker/build-push-action

inputs:
  metadata:
    description: Metadata output from docker/build-push-action
    required: true

outputs:
  image-uri:
    description: Image URI

runs:
  using: 'node20'
  main: 'dist/index.js'
