name: docker-build-metadata-action
description: Parse outputs of docker/metadata-action and docker/build-push-action

inputs:
  tags:
    description: Tags output from docker/metadata-action
    required: true
  digest:
    description: Digest output from docker/build-push-action
    required: false

outputs:
  image-uri:
    description: Image URI

runs:
  using: 'node20'
  main: 'dist/index.js'
